export const OPTIONS = [
    {
      displayText: "Fast/casual Food",
      options: [
        "McDonalds",
        "Subway",
        "Panda Express",
        "Canes",
        "Buffalo Wild Wings",
        "Dominos",
        "Jersey Mikes",
        "Taco truck",
        "Jack in the box",
        "In-n-Out",
        "Pho",
        "Sushi",
        "Poke",
        "Jollibee",
        "Dave's hot chicken",  
        "Chipotle",
        "Waba-grill",
        "Blaze Pizza",
        "Katsu Bar",
        "Nguyen's Kitchen",
        "Mr Katsu",
      ],
    },
    {
      displayText: "Video-Games",
      options: [
        "Mario Party",
        "Mario Kart",
        "Stardew Valley",
        "Overcooked",
        "Smash Bros.",
        "Skribble.io",
        "Minecraft",
        "BattleBlock Theatre",
        "Terraria",
        "Human Fall Flat",
        "Castle Crashers",
        "Uno",
      ],
    },
    {
      displayText: "Dining",
      options: [
        "Dim Sum",
        "Cheesecake Factory",
        "Olive Garden",
        "Buca Di Beppo",
        "BCD Tofu House",
        "KBBQ",
        "Shabu Shabu",
        "Boiling Point",
        "Zubies Dry Dock",
        "Red flame",
        "Gyu-Kaku JBBQ",
        "Fusion Corner",
        "Yard House",
        "Sevilla",
        "The Fifth",
        "Playa Mesa",
        "Din-Tai Fung",
        "Omoi Sushi",
      ],
    },
    {
      displayText: "Date ideas",
      options: [
        "Hiking",
        "Science Museum",
        "Live Music",
        "Live Play",
        "Comedy Club",
        "Mall",
        "Night Drive",
        "History Museum",
        "Movie night",
        "Drive in movie",
        "Casino",
        "Zoo",
        "Dave & Busters",
        "Aquarium",
        "The observatory",
        "Top of the world view",
        "Clubbing/dancing",
        "Mission Control",
        "TwoBit Circus",
        
      ],
    },
    {
      displayText: "Cooking",
      options: [
        "Fried Rice",
        "Quesadillas",
        "Mac and Cheese",
        "Spaghetti",
        "Pizza",
        "Tacos",
        "Chicken Alfredo",
        "Noodles",
        "Fajitas",
        "Breakfast",
        "Pasta",
        "Burgers",
        "Shrimp",
        "Tacos",
        "Chicken Wings",
        "Nachos",
      ],
    },
    {
      displayText: "Dessert",
      options: [
        "Dairy queen",
        "Afters ",
        "Crumble",
        "The loop",
        "Donuttery",
        "Dunkin",
        "Krispy Kreme",
        "85°C",
        "Somi-Somi",
        "Mochi-Donuts",
        "Cold Stone",
        "Baskin-Robins",
        
      ],
    },
  ];