export const OPTIONS = [
    {
      displayText: "Fast/casual Food",
      options: [
        "McDonalds",
        "Subway",
        "DQ Grill & Chill",
        "Panda Express",
        "Canes",
        "Buffalo Wild Wings",
        "Dominos",
        "Jersey Mikes",
        "Random mexican Taco truck",
        "Jack in the box",
        "In-n-Out",
        "Pho",
        "Sushi",
        "Poke",
        "Jollibee",
        "Dave's hot chicken",  
        "Chipotle",
        "Waba-grill",
      ],
    },
    {
      displayText: "Video-Games",
      options: [
        "Mario Party",
        "Mario Kart",
        "Stardew Valley",
        "Overcooked",
        "Smash Bros.",
        "Skribble.io",
        "Minecraft",
        "BattleBlock Theatre",
        "Terraria",
        "Human Fall Flat",
        "Castle Crashers",
      ],
    },
    {
      displayText: "Dining",
      options: [
        "Cheesecake Factory",
        "Olive Garden",
        "Buca Di Beppo",
        "BCD Tofu House",
        "Kbbq",
        "Shabu Shabu",
        "Boiling Point",
        "Zubies Dry Dock",
        "Red flame",
      ],
    },
    {
      displayText: "Date ideas",
      options: [
        "Hiking",
        "Science Museum",
        "Live Music",
        "Play",
        "Comedy Club",
        "Mall",
        "Night Drive",
        "History Museum",
        "Movie night",
        "Drive in movie",
        "Casino",
        "Zoo",
        "Dave & Busters",
        "Aquarium",
        "The observatory",
        "Top of the world view",
        "Clubbing/dancing",
      ],
    },
    {
      displayText: "Cooking",
      options: [
        "Fried Rice",
        "Quesadillas",
        "Mac and Cheese",
        "Spaghetti",
        "Pizza",
        "Tacos",
        "Chicken Alfredo",
        "Noodles",
        "Fajitas",
        "Breakfast",
        "Pasta",
        "Burgers",
        "Shrimp",
        "Tacos",
        "Chicken Wings",
        "Nachos",
      ],
    },
    {
      displayText: "Dessert",
      options: [
        "DQ ice cream",
        "Afters",
        "Crumble",
        "The loop",
        "Donuttery",
        "Dunkin",
        "Krispy Kreme",
        "85°C Bakery Cafe",
      ],
    },
  ];